### ISSUE TITLE
Package conflicts with latest update 1.3.1

### ISSUE THREAD

**Issue by Daivy03** [benjamindean/observatory#8]
When upgrading from 1.3.0 to 1.3.1 there is an conflict error with the package. Are you aware of this change? bc not saw any info in the latest changelog https://github.com/benjamindean/observatory/releases/tag/v1.3.1

**Comment by benjamindean** [comment]
Hey! So, it throws an error, huh? Looks like it's something with the package signature or something. I'll take a look.

**Comment by benjamindean** [comment]
> Thanks 👍

Yeah, apparently I forgot to configure singing for the .apk. 🤦 So, this and the next release you'll probably will have to re-install from scratch. Sorry about that! Will try to fix it next week.

**Comment by benjamindean** [comment]
@Daivy03 I re-uploaded the version 1.3.1 and now it's properly signed and hopefully won't require uninstalling in the future. Don't forget to re-download it!
